import = [
    "~/.config/alacritty/color-themes/base16-bright.toml"
]

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[window]
startup_mode = "Maximized"
# opacity = 0.9

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
	{ key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]

